---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
      MOCHA_FILE: "reports/mocha.xml"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-yarn-{{checksum ".circleci/config.yml"}}
      - run: .circleci/greenkeeper
      - run: yarn add -D nyc@11 @oclif/nyc-config@1 mocha-junit-reporter@1
      - run: ./bin/run --help
      - run: |
          mkdir -p reports
          $NYC yarn test --reporter mocha-junit-reporter
          $NYC report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: yarn global add @oclif/semantic-release@2 semantic-release@15
      - run: yarn --frozen-lockfile
      - run: |
          export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
          semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@heroku-cli/plugin-run":
    jobs:
      - node-latest
      - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
