environment:
  nodejs_version: "10"
  CI: 1
cache:
 - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
 - node_modules -> appveyor.yml

install:
  - ps: Install-Product node $env:nodejs_version x64
  - ls
  - yarn
test_script:
  - packages\cli\bin\run.cmd version
  - packages\cli\bin\run.cmd help
  - yarn test
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off
