clone_folder: C:\gopath\src\github.com\heroku\cli

environment:
  GOPATH: C:\gopath
  PATH: C:\gopath\bin;%PATH%

install:
  - go get -t -d -v ./...
  - go build -v

build: off

test_script:
  #- go test -v -race -timeout 30m ./...
  - go build -v ./...
