environment:
  nodejs_version: "9"
cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - bin\run.cmd version
  - bin\run.cmd help

build: off
