---
version: 2
jobs:
  node-latest: &test-build
    docker:
      - image: node:latest
    working_directory: /cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
            - v0-yarn-{{ .Environment.CIRCLE_JOB }}-master
      - run: yarn
      - run: yarn test --coverage
      - run: curl -s https://codecov.io/bash | bash
      - save_cache:
          key: v0-yarn-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /cli/node_modules
            - /usr/local/share/.cache/yarn
  node-8:
    <<: *test-build
    docker:
      - image: node:8
  node-6:
    <<: *test-build
    docker:
      - image: node:6

workflows:
  version: 2
  test:
    jobs:
      - node-latest
      - node-8
      - node-6
