name: Create CLI Release

on:
  workflow_dispatch:
    inputs:
      isProdTrigger:
        type: boolean
        description: Is this a production release?
        required: true
        default: false
  workflow_call:
    inputs:
      isProdTrigger:
        type: boolean
        description: Triggered from prod watcher?
        required: true
        default: false

jobs:
  get-version-channel:
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.getVersion.outputs.channel }}
      version: ${{ steps.getVersion.outputs.version }}
      isProdRelease: ${{ fromJSON(inputs.isProdTrigger) && !steps.getVersion.outputs.channel }}
    steps:
      - uses: actions/checkout@v3
      - id: getVersion
        uses: ./.github/actions/get-version-and-channel/
        with:
          path: './packages/cli/package.json'

  publish:
    needs: [get-version-channel]
    # channel is checked to avoid deploying from a malformed branch
    if: fromJSON(needs.get-version-channel.outputs.isProdRelease) || (!fromJSON(inputs.isProdTrigger) && !!needs.get-version-channel.outputs.channel)
    uses: ./.github/workflows/publish-npm.yml
    with:
      isProdRelease: ${{ fromJSON(needs.get-version-channel.outputs.isProdRelease) }}
    secrets: inherit

  pack-upload:
    needs: [ publish ]
    uses: ./.github/workflows/pack-upload.yml
    secrets: inherit

  promote:
    needs: [get-version-channel, pack-upload]
    if: needs.pack-upload.result == 'success'
    uses: ./.github/workflows/promote-release.yml
    with:
      version: ${{ needs.get-version-channel.outputs.version }}
      isProdRelease: ${{ fromJSON(needs.get-version-channel.outputs.isProdRelease) }}
    secrets: inherit
