name: Publish NPM

on:
  workflow_dispatch:
    inputs:
      isStableRelease:
        type: boolean
        description: Is this a stable/prod release?
        required: true
        default: false
      channel:
        type: choice
        description: If this is a prerelease, is it alpha or beta?
        options:
          - alpha
          - beta
        required: false
  workflow_call:
    inputs:
      isStableRelease:
        type: boolean
        description: Is this a stable/prod release?
        required: true
        default: false
      channel:
        type: string
        description: Release channel for prereleases
        required: false

jobs:
  publish-npm:
    # pub-hk-ubuntu-22.04- due to IP allow list issues with public repos: https://salesforce.quip.com/bu6UA0KImOxJ
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
      - run: npm ci
      - name: set NPM auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_KEY }}" > ~/.npmrc
      - name: Publish to NPM
        run: |
          PACKAGE_VERSION=$(node -e "console.log(require('./package.json').version)")
          PACKAGE_NAME=$(node -e "console.log(require('./package.json').name)")

          if npm view $PACKAGE_NAME@$PACKAGE_VERSION version &>/dev/null; then
            echo "Version $PACKAGE_VERSION already published to npm, skipping"
            exit 0
          fi

          if ${{ fromJSON(inputs.isStableRelease) }}
          then
            npm publish
          else
            npm publish --tag ${{ inputs.channel || 'beta' }}
          fi
        shell: bash
