name: Trigger Release

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
  push:
    branches:
      - prerelease/*

jobs:
  get-version-channel:
    outputs:
      tag: steps.distTag.outputs.tag
      version: steps.distTag.outputs.version
    steps:
      - uses: oclif/github-workflows/.github/actions/getPreReleaseTag@main
        id: distTag

  publish-pack-upload:
    # if (merged PR && is release branch) OR (prerelease branch && has a suffix on the package.json version)
    # suffix is checked to avoid deploying prod from a malformed prerelease branch
    if: (github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-') || (needs.get-version-channel.outputs.tag && startsWith(github.head_ref, 'prerelease/')))
    uses: ./.github/workflows/publish-pack-upload.yml
    with:
      isPreRelease: ${{ !!needs.get-version-channel.outputs.tag }}

  promote:
    needs: [publish-pack-upload]
    steps:
      - uses: oclif/github-workflows/.github/actions/getPreReleaseTag@main
        id: distTag
      - uses: ./.github/workflows/promote-release.yml
        with:
          version: steps.distTag.outputs.version
          channel: ${{ steps.distTag.outputs.tag || 'stable' }}
