name: Trigger Release

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
  push:
    branches:
      - prerelease/*

jobs:
  get-version-channel:
    if: contains(github.ref, 'release-') || contains(github.ref, 'prerelease/')
    runs-on: ubuntu-latest
    outputs:
      tag: steps.distTag.outputs.tag
      version: steps.distTag.outputs.version
    steps:
      - uses: actions/checkout@v3
      - id: distTag
        uses: ./.github/actions/getPreReleaseTag/
        with:
          path: './packages/cli/package.json'

  publish-pack-upload:
    # if (merged PR && is release branch) OR (prerelease branch && has a suffix on the package.json version)
    # suffix is checked to avoid deploying prod from a malformed prerelease branch
    if: (github.event.pull_request.merged == true && contains(github.ref, 'release-')) || (needs.get-version-channel.outputs.tag && contains(github.ref, 'prerelease/'))
    needs: [get-version-channel]
    uses: ./.github/workflows/publish-pack-upload.yml
    with:
      isPreRelease: ${{ !!needs.get-version-channel.outputs.tag }}

  promote:
    needs: [get-version-channel, publish-pack-upload]
#    if: needs.publish-pack-upload.outputs.success
    uses: ./.github/workflows/promote-release.yml
    with:
      version: needs.get-version-channel.outputs.version
      channel: ${{ needs.get-version-channel.outputs.tag || 'stable' }}
