name: Watch for release

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  start-release:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'release-')
    uses: ./.github/workflows/full-release-pipeline.yml
    secrets: inherit
    with:
      isProdTrigger: ${{ true }}
